server:
  port: 8080

#数据源配置
mysql:
  datasource:
    test1:
      url: jdbc:mysql://localhost:3306/atomikors01?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      minPoolSize: 3
      maxPoolSize: 25
      maxLifeTime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
    test2:
      url: jdbc:mysql://localhost:3306/atomikors02?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      minPoolSize: 3
      maxPoolSize: 25
      maxLifeTime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60

